<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Appartient extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Appartient_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'appartient/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'appartient/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'appartient/index.html';
            $config['first_url'] = base_url() . 'appartient/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Appartient_model->total_rows($q);
        $appartient = $this->Appartient_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'appartient_data' => $appartient,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('appartient_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Appartient_model->get_by_id($id);
        if ($row) {
            $data = array(
		'NNI' => $row->NNI,
		'id_Unite' => $row->id_Unite,
		'CCS' => $row->CCS,
	    );
            $this->load->view('appartient_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('appartient'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('appartient/create_action'),
	    'NNI' => set_value('NNI'),
	    'id_Unite' => set_value('id_Unite'),
	    'CCS' => set_value('CCS'),
	);
        $this->load->view('appartient_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Appartient_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('appartient'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Appartient_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('appartient/update_action'),
		'NNI' => set_value('NNI', $row->NNI),
		'id_Unite' => set_value('id_Unite', $row->id_Unite),
		'CCS' => set_value('CCS', $row->CCS),
	    );
            $this->load->view('appartient_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('appartient'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('NNI', TRUE));
        } else {
            $data = array(
	    );

            $this->Appartient_model->update($this->input->post('NNI', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('appartient'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Appartient_model->get_by_id($id);

        if ($row) {
            $this->Appartient_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('appartient'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('appartient'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('NNI', 'NNI', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Appartient.php */
/* Location: ./application/controllers/Appartient.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-21 12:59:51 */
/* http://harviacode.com */