<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ligne extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ligne_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'ligne/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'ligne/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'ligne/index.html';
            $config['first_url'] = base_url() . 'ligne/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Ligne_model->total_rows($q);
        $ligne = $this->Ligne_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'ligne_data' => $ligne,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('ligne_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Ligne_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_Ligne' => $row->id_Ligne,
		'id_Donnee' => $row->id_Donnee,
		'id_Modele_Ligne' => $row->id_Modele_Ligne,
	    );
            $this->load->view('ligne_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ligne'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('ligne/create_action'),
	    'id_Ligne' => set_value('id_Ligne'),
	    'id_Donnee' => set_value('id_Donnee'),
	    'id_Modele_Ligne' => set_value('id_Modele_Ligne'),
	);
        $this->load->view('ligne_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_Donnee' => $this->input->post('id_Donnee',TRUE),
		'id_Modele_Ligne' => $this->input->post('id_Modele_Ligne',TRUE),
	    );

            $this->Ligne_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('ligne'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Ligne_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('ligne/update_action'),
		'id_Ligne' => set_value('id_Ligne', $row->id_Ligne),
		'id_Donnee' => set_value('id_Donnee', $row->id_Donnee),
		'id_Modele_Ligne' => set_value('id_Modele_Ligne', $row->id_Modele_Ligne),
	    );
            $this->load->view('ligne_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ligne'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_Ligne', TRUE));
        } else {
            $data = array(
		'id_Donnee' => $this->input->post('id_Donnee',TRUE),
		'id_Modele_Ligne' => $this->input->post('id_Modele_Ligne',TRUE),
	    );

            $this->Ligne_model->update($this->input->post('id_Ligne', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('ligne'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Ligne_model->get_by_id($id);

        if ($row) {
            $this->Ligne_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('ligne'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ligne'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_Donnee', 'id donnee', 'trim|required');
	$this->form_validation->set_rules('id_Modele_Ligne', 'id modele ligne', 'trim|required');

	$this->form_validation->set_rules('id_Ligne', 'id_Ligne', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Ligne.php */
/* Location: ./application/controllers/Ligne.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-06 08:00:38 */
/* http://harviacode.com */