<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Methode_calcul extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Methode_calcul_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'methode_calcul/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'methode_calcul/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'methode_calcul/index.html';
            $config['first_url'] = base_url() . 'methode_calcul/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Methode_calcul_model->total_rows($q);
        $methode_calcul = $this->Methode_calcul_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'methode_calcul_data' => $methode_calcul,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('methode_calcul_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Methode_calcul_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_Methode_Calcul' => $row->id_Methode_Calcul,
		'libelle' => $row->libelle,
	    );
            $this->load->view('methode_calcul_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('methode_calcul'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('methode_calcul/create_action'),
	    'id_Methode_Calcul' => set_value('id_Methode_Calcul'),
	    'libelle' => set_value('libelle'),
	);
        $this->load->view('methode_calcul_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'libelle' => $this->input->post('libelle',TRUE),
	    );

            $this->Methode_calcul_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('methode_calcul'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Methode_calcul_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('methode_calcul/update_action'),
		'id_Methode_Calcul' => set_value('id_Methode_Calcul', $row->id_Methode_Calcul),
		'libelle' => set_value('libelle', $row->libelle),
	    );
            $this->load->view('methode_calcul_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('methode_calcul'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_Methode_Calcul', TRUE));
        } else {
            $data = array(
		'libelle' => $this->input->post('libelle',TRUE),
	    );

            $this->Methode_calcul_model->update($this->input->post('id_Methode_Calcul', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('methode_calcul'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Methode_calcul_model->get_by_id($id);

        if ($row) {
            $this->Methode_calcul_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('methode_calcul'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('methode_calcul'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('libelle', 'libelle', 'trim|required');

	$this->form_validation->set_rules('id_Methode_Calcul', 'id_Methode_Calcul', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Methode_calcul.php */
/* Location: ./application/controllers/Methode_calcul.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-28 15:16:09 */
/* http://harviacode.com */