<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Type_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Type_user_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'type_user/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'type_user/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'type_user/index.html';
            $config['first_url'] = base_url() . 'type_user/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Type_user_model->total_rows($q);
        $type_user = $this->Type_user_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'type_user_data' => $type_user,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('type_user_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Type_user_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_Type_User' => $row->id_Type_User,
		'libelle' => $row->libelle,
	    );
            $this->load->view('type_user_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('type_user'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('type_user/create_action'),
	    'id_Type_User' => set_value('id_Type_User'),
	    'libelle' => set_value('libelle'),
	);
        $this->load->view('type_user_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'libelle' => $this->input->post('libelle',TRUE),
	    );

            $this->Type_user_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('type_user'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Type_user_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('type_user/update_action'),
		'id_Type_User' => set_value('id_Type_User', $row->id_Type_User),
		'libelle' => set_value('libelle', $row->libelle),
	    );
            $this->load->view('type_user_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('type_user'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_Type_User', TRUE));
        } else {
            $data = array(
		'libelle' => $this->input->post('libelle',TRUE),
	    );

            $this->Type_user_model->update($this->input->post('id_Type_User', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('type_user'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Type_user_model->get_by_id($id);

        if ($row) {
            $this->Type_user_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('type_user'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('type_user'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('libelle', 'libelle', 'trim|required');

	$this->form_validation->set_rules('id_Type_User', 'id_Type_User', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Type_user.php */
/* Location: ./application/controllers/Type_user.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-21 12:59:52 */
/* http://harviacode.com */