<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_model extends CI_Model
{

    public $table = 'data';
    public $id = 'id_Data';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_structure_id($struct_id)
    {
        $query = $this->db->query('SELECT * FROM data WHERE id_Structure ='.$struct_id);
        return $query->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //TODO : rework cette fonction
    function get_lignes($numligne,$idFeuille,$idFichier)
    {
        $query = $this->db->query('SELECT * FROM data WHERE num_ligne_excel='.$numligne.' AND id_Structure IN(SELECT id_Structure FROM structure WHERE id_Feuille ='.$idFeuille.' AND id_Fichier ='.$idFichier.')');
        $resultarray = $query->result_array();

        return $resultarray;
    }


    function get_colonne($idFichier,$idFeuille,$idColonne)
    {
        $query = $this->db->query('SELECT * FROM data WHERE id_Structure IN(SELECT id_Structure FROM structure WHERE id_Feuille ='.$idFeuille.' AND id_Fichier ='.$idFichier.' AND id_Colonne ='.$idColonne.')');
        $resultarray = $query->result_array();

        return $resultarray;

    }

    function count_nb_ligne($idstruct)
    {
        $query = $this->db->query('SELECT COUNT(*) as nbligne FROM data WHERE id_Structure='.$idstruct);
        return $query->row();
    }

    function count_nb_colonne($idFichier,$idFeuille)
    {
        $req = "SELECT COUNT(*) as nbcol FROM structure WHERE id_Feuille= $idFeuille AND id_Fichier = $idFichier";
        $query = $this->db->query($req);
        return $query->row();
    }

    function count_nb_colonne2($idFeuille,$idFichier)
    {
        return $this->db->select('id_Structure')
            ->from('structure')
            ->where('id_Feuille',$idFeuille)
            ->where('id_Fichier',$idFichier)
            ->count_all_results();
    }


    function get_last_id()
    {
        return $this->db->insert_id();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_Data', $q);
        $this->db->or_like('data', $q);
        $this->db->or_like('num_ligne_excel', $q);
        $this->db->or_like('id_Structure', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_Data', $q);
	$this->db->or_like('data', $q);
	$this->db->or_like('num_ligne_excel', $q);
	$this->db->or_like('id_Structure', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_model.php */
/* Location: ./application/models/Data_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-28 15:16:08 */
/* http://harviacode.com */