<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Structure_model extends CI_Model
{

    public $table = 'structure';
    public $id = 'id_Structure';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_last_id()
    {
        return $this->db->insert_id();
    }

    function get_other_columns($idFichier,$idFeuille)
    {
        $query = $this->db->query('SELECT id_Colonne FROM structure WHERE id_Fichier ='.$idFichier.' AND id_Feuille ='.$idFeuille);
        $resultarray = $query->result_array();
        return($resultarray);
    }

    function get_all_column_id($idFichier,$idFeuille)
    {
        return $this->db->query("SELECT * FROM structure WHERE id_Fichier =".$idFichier." AND id_Feuille =".$idFeuille);
    }

    function getidFeuilleByidFichier($idFichier,$nomfeuille)
    {
        $this->load->model("Feuille_model");
        $feuille = new Feuille_model();
        $arrayIdByName = $feuille->getAllidFeuilleByName($nomfeuille);

        $query = $this->db->query("SELECT id_Feuille FROM structure WHERE id_Fichier =".$idFichier." AND id_Feuille IN".$arrayIdByName);
        $resultarray = $query->result_array();
        return($resultarray);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_Structure', $q);
	$this->db->or_like('id_Fichier', $q);
	$this->db->or_like('id_Colonne', $q);
	$this->db->or_like('id_Feuille', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_Structure', $q);
	$this->db->or_like('id_Fichier', $q);
	$this->db->or_like('id_Colonne', $q);
	$this->db->or_like('id_Feuille', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Structure_model.php */
/* Location: ./application/models/Structure_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-28 15:16:09 */
/* http://harviacode.com */